### ISSUE TITLE
Screenshot button

### ISSUE THREAD

**Issue by Ryyn-Sd** [rayyansaidi-com/app#4]
Can you do it so as soon as you hit the take a screenshot button, it will automatically ask you to print it?

**Comment by nthnchu** [comment]
This might be a bit tricky. I tried `window.open()` but electron doesn't have full support for that. My only idea (which is complicated) is to use electron's ipc to pass the data url of the canvas to the main process, create a browserWindow and load the data url. Then use `win.webContents.print();`. I'm more used to client side js rather than electron so it's a bit weird for me, but I can do it if this approach sounds good to you @Ryyn-Sd

**Comment by Ryyn-Sd** [comment]
OK. Do it!

**Comment by Ryyn-Sd** [comment]
Are you working on it?

**Comment by nthnchu** [comment]
Maybe later, I'll do it once I have more time

**Comment by Ryyn-Sd** [comment]
This will not be worked on.
